### ISSUE TITLE
No animation

### ISSUE THREAD

**Issue by MikAilis** [julkaar9/pynimate#13]
![image](https://github.com/julkaar9/pynimate/assets/100832845/344e2837-175c-4b8c-92d4-eb53ffcf5679)
I tried the example code, but nothing happend, I wonder what might be the cause of this

**Comment by julkaar9** [comment]
what ide are you using?

**Comment by MikAilis** [comment]
> 

pycharm

**Comment by julkaar9** [comment]
Ok I will take a look.

**Comment by julkaar9** [comment]
Seems like pycharm sciview cannot display animations https://youtrack.jetbrains.com/issue/PY-27233/Animation-not-updated-in-plots-window-scientific-view . 

A potential fix is to display the animation in a separate gui.

Add these two lines
```
import matplotlib
matplotlib.use("TkAgg")
```

**Comment by MikAilis** [comment]
oh，it's useful, thank u

**Comment by julkaar9** [comment]
closing the issue, if you have any other issue, please create a new one.
